spring:
  application:
    name: stockscan-api
  datasource:
    url: jdbc:h2:file:./data/stockscan;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

server:
  port: 8080
